apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv
  namespace: default
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data-backend
  storageClassName: manual

